### ISSUE TITLE
Need to install Zephyr SDK's QEMU into dispatcher container

### ISSUE THREAD

**Issue by pfalcon** [Linaro/lite-lava-docker-compose#30]
As one of the next steps towards networking (etc.) testing, we need a recent in general, and with any useful Zephyr patches, QEMU, in other words, coming from Zephyr SDK.

For reference, I tried to follow idea to use qemu_cortex_m3 + eth_stellaris target, but retesting it shows that it's in pretty broken state in Zephyr upstream: https://github.com/zephyrproject-rtos/zephyr/issues/13943 . qemu_x86 + eth_e1000 also has issues, while not so grave, but clearly visible even with manual testing, so likely will throw off any automated testing. mps2_an385 + eth_smsc911x however works pretty well (like, no issues known to me). And we need QEMU 4 to use that, getting that from Zephyr SDK is apparently the best option.

**Comment by galak** [comment]
> As one of the next steps towards networking (etc.) testing, we need a recent in general, and with any useful Zephyr patches, QEMU, in other words, coming from Zephyr SDK.
> 
> For reference, I tried to follow idea to use qemu_cortex_m3 + eth_stellaris target, but retesting it shows that it's in pretty broken state in Zephyr upstream: [zephyrproject-rtos/zephyr#13943](https://github.com/zephyrproject-rtos/zephyr/issues/13943) . qemu_x86 + eth_e1000 also has issues, while not so grave, but clearly visible even with manual testing, so likely will throw off any automated testing. mps2_an385 + eth_smsc911x however works pretty well (like, no issues known to me). And we need QEMU 4 to use that, getting that from Zephyr SDK is apparently the best option.

zephyr qemu is already installed in lava-dispatcher `/opt/zephyr-sdk/sysroots/x86_64-pokysdk-linux/usr/bin/`

**Comment by pfalcon** [comment]
cc @edmooring

**Comment by pfalcon** [comment]
> zephyr qemu is already installed in lava-dispatcher /opt/zephyr-sdk/sysroots/x86_64-pokysdk-linux/usr/bin/

Ah cool! So, it's included in zephyr-sdk-x86_64-hosttools-standalone-0.9.sh which we already install. I thought we'd need to come back to installing the whole SDK, which in turn revives older concerns of huge repetitive downloads.

But seems we're done here, closing.


For references, 2nd part of the puzzle, how to use that from LAVA, is tracked here: https://git.lavasoftware.org/lava/lava/issues/338 (and was discussed in email too).
